#!/usr/bin/env python3
"""Виконує логіку з lab-3.ipynb: метрики (report_metrics_generated.tex) і PNG для REPORT.tex."""
from __future__ import annotations

import io
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NB_PATH = ROOT / "lab-3.ipynb"
OUT_PATH = ROOT / "report_metrics_generated.tex"
FIG_DIR = ROOT / "figures"


def _cell_sources(nb: dict) -> list[str]:
    out = []
    for c in nb["cells"]:
        if c.get("cell_type") == "code":
            out.append("".join(c.get("source", [])))
    return out


def _find_cell(cells: list[str], predicate) -> str:
    for s in cells:
        if predicate(s):
            return s
    raise RuntimeError("required notebook code cell not found")


def _set_generation(src: str, generation: str) -> str:
    if generation not in ("separated", "overlap"):
        raise ValueError(generation)
    lines = []
    for line in src.splitlines():
        if re.match(r"^\s*GENERATION\s*=", line):
            lines.append(f'GENERATION = "{generation}"')
        else:
            lines.append(line)
    return "\n".join(lines) + "\n"


def notebook_namespace(generation: str) -> dict:
    """Повний namespace після імпортів, геометрії та клітини даних (як у ноутбуці)."""
    nb = json.loads(NB_PATH.read_text(encoding="utf-8"))
    cells = _cell_sources(nb)
    imp = _find_cell(cells, lambda s: "import numpy as np" in s and "matplotlib" in s)
    helpers = _find_cell(cells, lambda s: "class Petunin2DModel" in s and "def cross" in s)
    data = _find_cell(cells, lambda s: "CLASS_SPECS_SEPARATED" in s)
    data = _set_generation(data, generation)

    ns: dict = {}
    exec(imp, ns, ns)
    exec(helpers, ns, ns)
    buf = io.StringIO()
    old = sys.stdout
    try:
        sys.stdout = buf
        exec(data, ns, ns)
    finally:
        sys.stdout = old
    return ns


def _accuracy(results: list, pred_key: str) -> int:
    return sum(1 for r in results if r[pred_key] == r["true"])


def _run_pipeline(generation: str) -> dict:
    ns = notebook_namespace(generation)

    results = ns["classify_many"](
        ns["test_points"],
        ns["centroids"],
        ns["class_points"],
        ns["petunin_models_2d"],
        ns["test_points_3d"],
        ns["centroids_3d"],
        ns["petunin_models_3d"],
        ns["test_labels"],
    )
    names = list(ns["class_points"].keys())
    mismatch = [r for r in results if r["pred_L2"] != r["pred_L1"]]
    mismatch_pet = [r for r in results if r["pred_L2"] != r["pred_pet"]]
    mismatch_pet3 = [r for r in results if r["pred_L2_3d"] != r["pred_pet_3d"]]
    n = len(results)
    counts_l2 = {t: sum(1 for r in results if r["pred_L2"] == t) for t in names}
    counts_l1 = {t: sum(1 for r in results if r["pred_L1"] == t) for t in names}
    counts_pet = {t: sum(1 for r in results if r["pred_pet"] == t) for t in names}
    counts_l2_3d = {t: sum(1 for r in results if r["pred_L2_3d"] == t) for t in names}
    counts_pet3 = {t: sum(1 for r in results if r["pred_pet_3d"] == t) for t in names}
    centroids = ns["centroids"]
    return {
        "generation": generation,
        "n_test": n,
        "seed": int(ns.get("SEED", 24)),
        "n_per_class": int(ns.get("N_PER_CLASS", 100)),
        "acc_l2": _accuracy(results, "pred_L2"),
        "acc_l1": _accuracy(results, "pred_L1"),
        "acc_pet": _accuracy(results, "pred_pet"),
        "acc_l2_3d": _accuracy(results, "pred_L2_3d"),
        "acc_pet3": _accuracy(results, "pred_pet_3d"),
        "mismatch_l2_l1": len(mismatch),
        "mismatch_l2_pet": len(mismatch_pet),
        "mismatch_l2_pet3d": len(mismatch_pet3),
        "counts_l2": counts_l2,
        "counts_l1": counts_l1,
        "counts_pet": counts_pet,
        "counts_l2_3d": counts_l2_3d,
        "counts_pet3": counts_pet3,
        "centroids": {k: (float(v[0]), float(v[1])) for k, v in centroids.items()},
    }


def build_tex(sep: dict, ovl: dict) -> str:
    names = sorted(sep["counts_l2"].keys(), key=lambda x: (x != "Тип 1", x != "Тип 2", x))

    lines = [
        r"% --- AUTO-GENERATED by lab3/scripts/export_report_metrics.py ---",
        r"% Метрики + (разом зі скриптом) PNG у lab3/figures/. Не редагувати вручну.",
        r"% Оновити: python3 lab3/scripts/export_report_metrics.py",
        "",
        r"\newcommand{\LabThreeSeed}{" + str(sep["seed"]) + "}",
        r"\newcommand{\LabThreeNTrain}{" + str(sep["n_per_class"]) + "}",
        r"\newcommand{\LabThreeNTest}{" + str(sep["n_test"]) + "}",
        "",
        r"\begin{table}[H]",
        r"\centering",
        r"\renewcommand{\arraystretch}{1.15}",
        r"\begin{tabular}{|l|c|c|}",
        r"\hline",
        r"\textbf{Метод} & \textbf{Розділені} & \textbf{Перекриття} \\",
        r"\hline",
        rf"$L2$ & {sep['acc_l2']} з {sep['n_test']} & {ovl['acc_l2']} з {ovl['n_test']} \\",
        r"\hline",
        rf"$L1$ & {sep['acc_l1']} з {sep['n_test']} & {ovl['acc_l1']} з {ovl['n_test']} \\",
        r"\hline",
        rf"Петунін 2D & {sep['acc_pet']} з {sep['n_test']} & {ovl['acc_pet']} з {ovl['n_test']} \\",
        r"\hline",
        rf"$L2$ у 3D & {sep['acc_l2_3d']} з {sep['n_test']} & {ovl['acc_l2_3d']} з {ovl['n_test']} \\",
        r"\hline",
        rf"Петунін 3D & {sep['acc_pet3']} з {sep['n_test']} & {ovl['acc_pet3']} з {ovl['n_test']} \\",
        r"\hline",
        r"\end{tabular}",
        r"\caption{Точність класифікації на тестовому наборі (істинні мітки типів)}",
        r"\label{tab:lab3accuracy}",
        r"\end{table}",
        "",
        r"\begin{table}[H]",
        r"\centering",
        r"\renewcommand{\arraystretch}{1.15}",
        r"\begin{tabular}{|l|c|c|}",
        r"\hline",
        r"\textbf{Пара порівняння} & \textbf{Розділені} & \textbf{Перекриття} \\",
        r"\hline",
        rf"$L2$ vs $L1$ & {sep['mismatch_l2_l1']} з {sep['n_test']} & {ovl['mismatch_l2_l1']} з {ovl['n_test']} \\",
        r"\hline",
        rf"$L2$ vs Петунін 2D & {sep['mismatch_l2_pet']} з {sep['n_test']} & {ovl['mismatch_l2_pet']} з {ovl['n_test']} \\",
        r"\hline",
        rf"$L2$ (3D) vs Петунін 3D & {sep['mismatch_l2_pet3d']} з {sep['n_test']} & {ovl['mismatch_l2_pet3d']} з {ovl['n_test']} \\",
        r"\hline",
        r"\end{tabular}",
        r"\caption{Зведення розбіжностей індивідуальних рішень на тестовому наборі}",
        r"\label{tab:lab3mismatch}",
        r"\end{table}",
        "",
        r"\begin{table}[H]",
        r"\centering",
        r"\renewcommand{\arraystretch}{1.15}",
        r"\begin{tabular}{|l|r|r|r|r|}",
        r"\hline",
        r"\textbf{Клас} & \multicolumn{2}{c|}{\textbf{Розділені ($x_c,\,y_c$)}} & \multicolumn{2}{c|}{\textbf{Перекриття ($x_c,\,y_c$)}} \\",
        r"\hline",
        r" & $x_c$ & $y_c$ & $x_c$ & $y_c$ \\",
        r"\hline",
    ]
    for name in names:
        xs, ys = sep["centroids"][name]
        xo, yo = ovl["centroids"][name]
        lines.append(
            rf"{name} & {xs:.4f} & {ys:.4f} & {xo:.4f} & {yo:.4f} \\" + "\n" + r"\hline"
        )
    lines.extend(
        [
            r"\end{tabular}",
            r"\caption{Центроїди класів у площині $(x,y)$ для двох режимів генерації}",
            r"\label{tab:lab3centroids}",
            r"\end{table}",
            "",
            r"\begin{table}[H]",
            r"\centering",
            r"\renewcommand{\arraystretch}{1.12}",
        r"\begin{tabular}{|l|" + "c|" * len(names) + "}",
        r"\hline",
        r"\textbf{Метод} & " + " & ".join([rf"\textbf{{{n}}}" for n in names]) + r" \\",
        r"\hline",
        r"$L2$ & " + " & ".join(str(sep["counts_l2"][t]) for t in names) + r" \\",
        r"\hline",
        r"$L1$ & " + " & ".join(str(sep["counts_l1"][t]) for t in names) + r" \\",
        r"\hline",
        r"Петунін 2D & " + " & ".join(str(sep["counts_pet"][t]) for t in names) + r" \\",
        r"\hline",
        r"$L2$ у 3D & " + " & ".join(str(sep["counts_l2_3d"][t]) for t in names) + r" \\",
        r"\hline",
        r"Петунін 3D & " + " & ".join(str(sep["counts_pet3"][t]) for t in names) + r" \\",
        r"\hline",
        r"\end{tabular}",
        r"\caption{Кількість передбачень по класах (режим \textit{розділені}; тест $34{+}33{+}33$)}",
        r"\label{tab:lab3predsep}",
        r"\end{table}",
        "",
        r"\begin{table}[H]",
        r"\centering",
        r"\renewcommand{\arraystretch}{1.12}",
        r"\begin{tabular}{|l|" + "c|" * len(names) + "}",
        r"\hline",
        r"\textbf{Метод} & " + " & ".join([rf"\textbf{{{n}}}" for n in names]) + r" \\",
        r"\hline",
        r"$L2$ & " + " & ".join(str(ovl["counts_l2"][t]) for t in names) + r" \\",
        r"\hline",
        r"$L1$ & " + " & ".join(str(ovl["counts_l1"][t]) for t in names) + r" \\",
        r"\hline",
        r"Петунін 2D & " + " & ".join(str(ovl["counts_pet"][t]) for t in names) + r" \\",
        r"\hline",
        r"$L2$ у 3D & " + " & ".join(str(ovl["counts_l2_3d"][t]) for t in names) + r" \\",
        r"\hline",
        r"Петунін 3D & " + " & ".join(str(ovl["counts_pet3"][t]) for t in names) + r" \\",
        r"\hline",
        r"\end{tabular}",
        r"\caption{Кількість передбачень по класах (режим \textit{перекриття}; тест $34{+}33{+}33$)}",
        r"\label{tab:lab3predovl}",
        r"\end{table}",
        ]
    )
    return "\n".join(lines) + "\n"


def export_figures() -> None:
    """PNG з тієї ж логіки, що клітини 5, 12 та проекції 3D у lab-3.ipynb (matplotlib, Agg)."""
    os.environ.setdefault("MPLBACKEND", "Agg")
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import numpy as np
    from matplotlib.colors import BoundaryNorm, ListedColormap
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

    FIG_DIR.mkdir(parents=True, exist_ok=True)
    titles = {
        "separated": "Класи: розділені хмари (мало перекриття)",
        "overlap": "Класи: часткове перекриття множин",
    }

    def scatter_test_labeled(ax, test_points, test_labels, class_specs, *, s=14, alpha=0.9, marker="x"):
        labels = np.asarray(test_labels)
        for name, spec in class_specs.items():
            mask = labels == name
            if not np.any(mask):
                continue
            ax.scatter(
                test_points[mask, 0],
                test_points[mask, 1],
                s=s,
                alpha=alpha,
                color=spec["color"],
                marker=marker,
                linewidths=0.8,
                label=f"тест ({name})",
            )

    def ellipsoid_parametric(center, half, rho, n_u=16, n_v=32):
        u = np.linspace(0.0, np.pi, n_u)
        v = np.linspace(0.0, 2.0 * np.pi, n_v)
        U, V = np.meshgrid(u, v)
        nx = np.sin(U) * np.cos(V)
        ny = np.sin(U) * np.sin(V)
        nz = np.cos(U)
        X = center[0] + rho * half[0] * nx
        Y = center[1] + rho * half[1] * ny
        Z = center[2] + rho * half[2] * nz
        return X, Y, Z

    def plot_polyline3d(ax, wx, wy, wz, color, lw=0.7):
        xs, ys, zs = [], [], []
        for x, y, z in zip(wx, wy, wz):
            if x is None:
                if xs:
                    ax.plot(xs, ys, zs, color=color, linewidth=lw, alpha=0.75)
                xs, ys, zs = [], [], []
            else:
                xs.append(x)
                ys.append(y)
                zs.append(z)
        if xs:
            ax.plot(xs, ys, zs, color=color, linewidth=lw, alpha=0.75)

    def bisector_plane_mesh(c0, c1, span, n=14):
        m = 0.5 * (c0 + c1)
        nvec = c1 - c0
        ln = np.linalg.norm(nvec)
        if ln < 1e-12:
            return None, None, None
        nvec = nvec / ln
        aux = np.array([0.0, 0.0, 1.0]) if abs(nvec[2]) < 0.9 else np.array([1.0, 0.0, 0.0])
        e1 = np.cross(nvec, aux)
        e1 = e1 / (np.linalg.norm(e1) + 1e-15)
        e2 = np.cross(nvec, e1)
        su = np.linspace(-span, span, n)
        sv = np.linspace(-span, span, n)
        U, V = np.meshgrid(su, sv)
        X = m[0] + U * e1[0] + V * e2[0]
        Y = m[1] + U * e1[1] + V * e2[1]
        Z = m[2] + U * e1[2] + V * e2[2]
        return X, Y, Z

    for gen in ("separated", "overlap"):
        ns = notebook_namespace(gen)
        class_points = ns["class_points"]
        class_points_3d = ns["class_points_3d"]
        class_specs = ns["class_specs"]
        centroids = ns["centroids"]
        test_points = ns["test_points"]
        test_points_3d = ns["test_points_3d"]
        test_labels = ns["test_labels"]
        petunin_models_2d = ns["petunin_models_2d"]

        # --- 2D: навчальні + центроїди + тест (як клітина 5 ноутбука) ---
        fig, ax = plt.subplots(figsize=(9, 6))
        for name, pts in class_points.items():
            ax.scatter(
                pts[:, 0],
                pts[:, 1],
                s=18,
                alpha=0.7,
                color=class_specs[name]["color"],
                label=f"{name} ({class_specs[name]['mode']})",
            )
        for name, c in centroids.items():
            ax.scatter(
                c[0],
                c[1],
                s=230,
                marker="X",
                edgecolor="black",
                linewidth=1.2,
                color=class_specs[name]["color"],
            )
            ax.text(c[0] + 0.15, c[1] + 0.15, f"центр {name}")
        scatter_test_labeled(ax, test_points, test_labels, class_specs, s=42, alpha=0.95)
        ax.set_title(titles[gen])
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.axis("equal")
        ax.legend(loc="best", fontsize=8)
        fig.tight_layout()
        fig.savefig(FIG_DIR / f"lab3_scatter_{gen}.png", dpi=200, facecolor="white")
        plt.close(fig)

        # --- 2D: еліпси Петуніна (як клітина 12) ---
        fig, ax = plt.subplots(figsize=(11, 9))
        for name, pts in class_points.items():
            ax.scatter(
                pts[:, 0],
                pts[:, 1],
                s=12,
                alpha=0.45,
                color=class_specs[name]["color"],
                label=name,
            )
        for name, model in petunin_models_2d.items():
            col = class_specs[name]["color"]
            ru = np.unique(model.radii_ordered)
            if len(ru) > 28:
                ru = np.sort(np.unique(ru[np.linspace(0, len(ru) - 1, 28, dtype=int)]))
            for r in ru:
                xy = model.ellipse_xy(r, n_phi=96)
                ax.plot(xy[:, 0], xy[:, 1], color=col, lw=0.9, alpha=0.7)
        scatter_test_labeled(ax, test_points, test_labels, class_specs, s=22, alpha=0.9)
        ax.set_title("Еліпси Петуніна (lab1) для кожного типу на одній площині $(x,y)$")
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.axis("equal")
        ax.legend(loc="best", fontsize=8)
        fig.tight_layout()
        fig.savefig(FIG_DIR / f"lab3_petunin2d_{gen}.png", dpi=200, facecolor="white")
        plt.close(fig)

        # --- 2D: карти рішень L2 та L1 (центроїдний класифікатор на сітці) ---
        names2 = list(centroids.keys())
        cent2 = np.array([centroids[n] for n in names2])
        all2 = np.vstack(list(class_points.values()))
        pad2 = 1.2
        x0, x1 = all2[:, 0].min() - pad2, all2[:, 0].max() + pad2
        y0, y1 = all2[:, 1].min() - pad2, all2[:, 1].max() + pad2
        gx, gy = np.meshgrid(np.linspace(x0, x1, 260), np.linspace(y0, y1, 260))
        pts2 = np.stack([gx.ravel(), gy.ravel()], axis=1)
        cmap2 = ListedColormap([class_specs[names2[i]]["color"] for i in range(len(names2))])
        norm2 = BoundaryNorm(np.arange(-0.5, len(names2) + 0.5, 1), cmap2.N)

        d_l2g = np.linalg.norm(pts2[:, None, :] - cent2[None, :, :], axis=2)
        z_l2 = np.argmin(d_l2g, axis=1).reshape(gx.shape)
        fig, ax = plt.subplots(figsize=(9, 7))
        ax.pcolormesh(gx, gy, z_l2, cmap=cmap2, norm=norm2, shading="auto", alpha=0.32)
        for name, pts in class_points.items():
            ax.scatter(
                pts[:, 0],
                pts[:, 1],
                s=14,
                alpha=0.75,
                color=class_specs[name]["color"],
                edgecolors="k",
                linewidths=0.15,
            )
        ax.scatter(cent2[:, 0], cent2[:, 1], s=200, c="white", marker="X", edgecolors="black", linewidths=1.1, zorder=5)
        scatter_test_labeled(ax, test_points, test_labels, class_specs, s=18, alpha=0.85, marker="x")
        ax.set_title(f"$L2$ до центроїдів (фон = argmin) — {titles[gen]}")
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.set_aspect("equal")
        fig.tight_layout()
        fig.savefig(FIG_DIR / f"lab3_l2regions_{gen}.png", dpi=200, facecolor="white")
        plt.close(fig)

        d_l1g = np.sum(np.abs(pts2[:, None, :] - cent2[None, :, :]), axis=2)
        z_l1 = np.argmin(d_l1g, axis=1).reshape(gx.shape)
        fig, ax = plt.subplots(figsize=(9, 7))
        ax.pcolormesh(gx, gy, z_l1, cmap=cmap2, norm=norm2, shading="auto", alpha=0.32)
        for name, pts in class_points.items():
            ax.scatter(
                pts[:, 0],
                pts[:, 1],
                s=14,
                alpha=0.75,
                color=class_specs[name]["color"],
                edgecolors="k",
                linewidths=0.15,
            )
        ax.scatter(cent2[:, 0], cent2[:, 1], s=200, c="white", marker="X", edgecolors="black", linewidths=1.1, zorder=5)
        scatter_test_labeled(ax, test_points, test_labels, class_specs, s=18, alpha=0.85, marker="x")
        ax.set_title(f"$L1$ до центроїдів (фон = argmin) — {titles[gen]}")
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.set_aspect("equal")
        fig.tight_layout()
        fig.savefig(FIG_DIR / f"lab3_l1regions_{gen}.png", dpi=200, facecolor="white")
        plt.close(fig)

        # --- Проекції 3D на площини (matplotlib, як у клітині 13 ноутбука) ---
        fig2, axes = plt.subplots(1, 3, figsize=(12, 4))
        for ax, (i, j, li, lj) in zip(
            axes,
            [(0, 1, "x", "y"), (0, 2, "x", "z"), (1, 2, "y", "z")],
        ):
            for name, pts in class_points_3d.items():
                ax.scatter(
                    pts[:, i],
                    pts[:, j],
                    s=8,
                    alpha=0.4,
                    color=class_specs[name]["color"],
                    label=name,
                )
            labels3 = np.asarray(test_labels)
            for name, spec in class_specs.items():
                mask = labels3 == name
                ax.scatter(
                    test_points_3d[mask, i],
                    test_points_3d[mask, j],
                    s=12,
                    c=spec["color"],
                    alpha=0.5,
                    marker="x",
                )
            ax.set_xlabel(li)
            ax.set_ylabel(lj)
            ax.set_title(f"{li}{lj}")
            ax.axis("equal")
        axes[0].legend(loc="best", fontsize=7)
        fig2.suptitle(f"Проекції 3D-даних: {titles[gen]}", fontsize=11, y=1.02)
        fig2.tight_layout()
        fig2.savefig(FIG_DIR / f"lab3_projections_{gen}.png", dpi=200, facecolor="white")
        plt.close(fig2)

        # --- 3D: площини рівної L2-відстані між центроїдами + каркас Петуніна ---
        petunin_models_3d = ns["petunin_models_3d"]
        centroids_3d = ns["centroids_3d"]
        names3 = list(centroids_3d.keys())
        C3 = np.array([centroids_3d[n] for n in names3])
        all3 = np.vstack(list(class_points_3d.values()))
        span3 = float(np.max(all3.max(axis=0) - all3.min(axis=0))) * 0.75 + 2.0
        plane_cols = ["#bbbbbb", "#cccccc", "#aaaaaa"]

        fig = plt.figure(figsize=(10.5, 8.5))
        ax = fig.add_subplot(111, projection="3d")
        for k, (i, j) in enumerate([(0, 1), (0, 2), (1, 2)]):
            X, Y, Z = bisector_plane_mesh(C3[i], C3[j], span3, n=16)
            if X is None:
                continue
            ax.plot_surface(X, Y, Z, color=plane_cols[k % 3], alpha=0.22, linewidth=0, antialiased=True)

        for name, pts in class_points_3d.items():
            ax.scatter(
                pts[:, 0],
                pts[:, 1],
                pts[:, 2],
                s=5,
                alpha=0.38,
                color=class_specs[name]["color"],
                label=name,
            )
        ax.scatter(
            test_points_3d[:, 0],
            test_points_3d[:, 1],
            test_points_3d[:, 2],
            s=2,
            c="k",
            alpha=0.12,
        )

        for name, m3 in petunin_models_3d.items():
            col = class_specs[name]["color"]
            ru = np.unique(m3.radii_ordered)
            if len(ru) > 7:
                ru = np.sort(np.unique(ru[np.linspace(0, len(ru) - 1, 7, dtype=int)]))
            for rho in ru:
                X, Y, Z = ellipsoid_parametric(m3.center, m3.half, rho)
                wx, wy, wz = [], [], []
                for ii in range(X.shape[0]):
                    wx.extend(X[ii, :].tolist())
                    wy.extend(Y[ii, :].tolist())
                    wz.extend(Z[ii, :].tolist())
                    wx.append(None)
                    wy.append(None)
                    wz.append(None)
                for jj in range(X.shape[1]):
                    wx.extend(X[:, jj].tolist())
                    wy.extend(Y[:, jj].tolist())
                    wz.extend(Z[:, jj].tolist())
                    wx.append(None)
                    wy.append(None)
                    wz.append(None)
                plot_polyline3d(ax, wx, wy, wz, col, lw=0.65)

        ax.set_title(f"3D: межі $L2$ (площини між центроїдами) + Петунін — {titles[gen]}")
        ax.set_xlabel("x")
        ax.set_ylabel("y")
        ax.set_zlabel("z")
        ax.legend(loc="upper left", fontsize=7)
        fig.tight_layout()
        fig.savefig(FIG_DIR / f"lab3_3d_l2_pet_{gen}.png", dpi=200, facecolor="white")
        plt.close(fig)

    print("Wrote figures to", FIG_DIR)


def main() -> None:
    sep = _run_pipeline("separated")
    ovl = _run_pipeline("overlap")
    tex = build_tex(sep, ovl)
    OUT_PATH.write_text(tex, encoding="utf-8")
    print("Wrote", OUT_PATH, "OK")
    export_figures()


if __name__ == "__main__":
    main()
